name: todomanage
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-149.3.beta

dependencies:
  # animated_bottom_navigation_bar: ^1.3.3
  cloud_firestore: ^5.4.4
  # dropdown_search: ^6.0.1
  device_preview: ^1.2.0
  dropdown_button2: ^2.3.9
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  # flutter_floating_bottom_bar: ^1.2.1+1
  go_router: ^14.2.8
  intl: ^0.19.0
  permission_handler: ^11.3.1
  popover: ^0.3.1
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  speech_to_text: ^7.0.0
  syncfusion_flutter_charts: ^27.1.53
  syncfusion_flutter_datepicker: ^27.1.51
  timeline_tile: ^2.0.0
  url_launcher: ^6.3.0
  google_nav_bar: ^5.0.7
  toggle_switch: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
